version: '3.9'

services:
  db:
    image: mcr.microsoft.com/azure-sql-edge #mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "1433:1433"
    secrets:
      - db_password


  server:
    image: projectbankserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ConnectionStrings__ProjectBank:
      BlobContainerUri: https://projectbankstorage.blob.core.windows.net/azurecontainer
      ASPNETCORE_URLS: https://+;http://+
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: localhost
    ports:
      - "5077:80"
      - "7207:443"
    depends_on:
      - db
    secrets:
      - source: connection_string
        target: ConnectionStrings__ProjectBank
      - source: storage_key
        target: StorageAccountKey

    volumes:
      - "~/.aspnet/https:/https:ro" #Should be cross platform
      #- "${HOME}/.aspnet/https:/https/" #Mac/linux
      #- %USERPROFILE%\.aspnet\https:/https/ #Windows
      #- ../../../.aspnet/https:/https/ #Default. Locate the certificate by going backwards 

secrets:
  db_password:
    file: ./.local/db_password.txt
  connection_string:
    file: ./.local/connection_string.txt
  storage_key:
    file: ./.local/storage_key.txt
